# Django' secret key
secret_key = "<generated key>"

#
allowed_hosts = [
    "quizz.ehloenology.ch"
]

internal_ips = [
    "127.0.0.1"
]


[social_auth]

# These credentials are from a test applications only allowed to run on 127.0.0.1:8000
google_oauth2_key = "831444856202-r8sdhk86tsjjttqc279ostqb736li02d.apps.googleusercontent.com"
google_oauth2_secret = "K9clphncnjavFL2pW-754wsb"
