# A secret key for a particular Django installation. This is used to provide
# cryptographic signing, and should be set to a unique, unpredictable value.
# https://docs.djangoproject.com/en/2.1/ref/settings/#std:setting-SECRET_KEY
secret_key = "<generated key>"

# A list of strings representing the host/domain names that this Django site
# can serve. This is a security measure to prevent HTTP Host header attacks,
# which are possible even under many seemingly-safe web server configurations.
# https://docs.djangoproject.com/en/2.1/ref/settings/#allowed-hosts
allowed_hosts = [
    "quizz.ehloenology.ch"
]

# A list of IP addresses, as strings, that have some debug capabilities.
# https://docs.djangoproject.com/en/2.1/ref/settings/#internal-ips
internal_ips = [
    "127.0.0.1"
]


[database]

# For details on these credentials, see
# https://docs.djangoproject.com/en/2.1/ref/settings/#databases
engine = "django.db.backends.mysql"
name = ""
user = ""
password = ""
host = ""
port = ""


[cache]

# For details on these credentials, see
# https://docs.djangoproject.com/fr/2.1/topics/cache/#setting-up-the-cache
backend = "django.core.cache.backends.filebased.FileBasedCache"
location = "/var/tmp/ehl-oenology-quizz-cache"


[social_auth]

# These credentials are from a test applications only allowed to run on 127.0.0.1:8000
google_oauth2_key = "831444856202-r8sdhk86tsjjttqc279ostqb736li02d.apps.googleusercontent.com"
google_oauth2_secret = "K9clphncnjavFL2pW-754wsb"
