# Generated by Django 2.1.2 on 2018-10-06 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=256)),
                ('is_correct', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(0, 'Open question (or multiple-choices with an “other” option)'), (1, 'Multiple choices question')])),
                ('question', models.CharField(max_length=256, verbose_name='Question')),
                ('open_valid_answer', models.CharField(blank=True, default=None, max_length=256, null=True, verbose_name="Question's valid answer if this is an open question or if this is a MCQ and the answer is not in the proposed answers")),
                ('answer_comment', models.TextField()),
                ('proposed_answers', models.ManyToManyField(to='quizz.Answer', verbose_name="Question's proposed answers")),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name of the tag')),
                ('slug', models.SlugField(editable=False)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='tags',
            field=models.ManyToManyField(to='quizz.Tag', verbose_name="Question's tags for quizz generation filtering"),
        ),
    ]
