# Generated by Django 2.1.2 on 2018-10-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='type',
        ),
        migrations.AddField(
            model_name='question',
            name='is_mcq',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
