# Generated by Django 2.1.7 on 2019-03-04 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz', '0003_hierarchical-mptt-tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='creator',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions_created', to=settings.AUTH_USER_MODEL, verbose_name='Creator'),
        ),
        migrations.AddField(
            model_name='question',
            name='editors',
            field=models.ManyToManyField(editable=False, related_name='questions_edited', to=settings.AUTH_USER_MODEL, verbose_name='Editors'),
        ),
        migrations.AddField(
            model_name='question',
            name='imported',
            field=models.BooleanField(default=False, editable=False, verbose_name='Was this question imported?'),
        ),
    ]
