# Generated by Django 2.1.7 on 2019-03-04 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0004_questions-origin-and-edits-metadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Contest name')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='quizz.Contest', verbose_name='Contest from which this question is taken'),
        ),
    ]
