# Generated by Django 2.1.7 on 2019-03-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0005_questions-contests-source'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contest',
            options={'ordering': ('name',)},
        ),
        migrations.AlterModelOptions(
            name='questionlocale',
            options={'ordering': ('name',)},
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_comment',
            field=models.TextField(blank=True, max_length=65536, null=True, verbose_name="Answer's comment"),
        ),
    ]
