# Generated by Django 2.1.7 on 2019-03-07 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

import quizz.models
import quizz.models.quizzes


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz', '0006_nullable-answer-comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='The moment when this quizz was started')),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='The moment when this quizz was finished')),
            ],
        ),
        migrations.CreateModel(
            name='QuizzAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_checked', models.BooleanField(verbose_name='Was this answer checked?')),
                ('linked_to', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='linked_to_by_users', to='quizz.Answer', verbose_name='The answer linked to this answer by the user')),
                ('proposed_answer', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='quizz.Answer', verbose_name='The answer that was proposed to the user')),
            ],
        ),
        migrations.CreateModel(
            name='QuizzQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.SmallIntegerField(verbose_name='The ordering of the question in the quizz')),
                ('started_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='The moment when this question was started')),
                ('finished_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='The moment when this quizz was finished')),
                ('open_answer', models.TextField(blank=True, default=None, max_length=1024, null=True, verbose_name='Open answer')),
                ('success', models.CharField(blank=True, choices=[(quizz.models.QuestionSuccess('PERFECT'), 'PERFECT'), (
                quizz.models.QuestionSuccess('ALMOST'), 'ALMOST'), (quizz.models.QuestionSuccess('FAILED'), 'FAILED')], default=None, max_length=8, null=True, verbose_name='Was this question correctly answered?')),
                ('points', models.SmallIntegerField(blank=True, default=None, null=True, verbose_name='The points earned for this question')),
                ('answers', models.ManyToManyField(to='quizz.QuizzAnswer', verbose_name='All non-open answers')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_answers', to='quizz.Question', verbose_name='The question')),
            ],
        ),
        migrations.AddField(
            model_name='quizz',
            name='questions',
            field=models.ManyToManyField(to='quizz.QuizzQuestion', verbose_name='The questions in this quizz'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to=settings.AUTH_USER_MODEL, verbose_name='The user passing this quizz'),
        ),
    ]
