# Generated by Django 2.1.7 on 2019-03-09 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0008_same-field-type-for-open-answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='ip',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True, verbose_name='The IP address of the user passing this quizz'),
        ),
        migrations.AddField(
            model_name='quizz',
            name='slug',
            field=models.SlugField(default='', max_length=8, verbose_name="The quizz' slug"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizz',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='The moment when this quizz was finished'),
        ),
        migrations.AlterField(
            model_name='quizzquestion',
            name='finished_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='The moment when this quizz was finished'),
        ),
        migrations.AlterField(
            model_name='quizzquestion',
            name='started_at',
            field=models.DateTimeField(blank=True, default=None, editable=False, null=True, verbose_name='The moment when this question was started'),
        ),
    ]
