# Generated by Django 2.1.7 on 2019-03-12 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0009_add-slug-and-ip-to-quizzes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzquestion',
            name='points',
            field=models.FloatField(blank=True, default=None, null=True, verbose_name='The points earned for this question'),
        ),
    ]
