# Generated by Django 2.1.7 on 2019-03-12 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizz', '0010_quizz-points-are-floats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizzanswer',
            name='is_checked',
            field=models.BooleanField(blank=True, null=True, verbose_name='Was this answer checked?'),
        ),
        migrations.AlterField(
            model_name='quizzanswer',
            name='linked_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='linked_to_by_users', to='quizz.Answer', verbose_name='The answer linked to this answer by the user'),
        ),
    ]
