# Generated by Django 2.1.7 on 2019-03-18 18:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quizz.models
import quizz.models.users
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz', '0011_quizz-answers-fields-are-nullable'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to=quizz.models.users.profile_image_path, verbose_name='User picture')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='quizzquestion',
            name='success',
            field=models.CharField(blank=True, choices=[('PERFECT', quizz.models.QuestionSuccess('PERFECT')), ('ALMOST', quizz.models.QuestionSuccess('ALMOST')), ('FAILED', quizz.models.QuestionSuccess('FAILED'))], default=None, max_length=8, null=True, verbose_name='Was this question correctly answered?'),
        ),
    ]
